### ISSUE TITLE
Spanish (Español) <es-es.cfg>

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/MoneroFlags#17]
# Localization - ![Español][ES] Spanish (Español) <es-es.cfg>

## To Be Done by :octocat: contributor

* Some helpful reading
  * [Readme on localization][lclztn]
  * [Quickstart guide to localization][qs]
  * these should help guide you
  * both are in markdown {text}
  * if you are feeling very helpful, kindly translate these as well. ;P
* GameData (done by contributor)
  * [x] add Localization\<es-es.cfg> 🗃️
* Translation
  * [x] ![Español][ES] Spanish (Español) <es-es.cfg>

1. Fork this repo
2. Create a branch name it 'translations' or localizations (suggestions)
3. goto `GameData/.../Localization/`
4. copy <en-us.cfg>
5. rename to <es-es.cfg>
6. open the file and translate everything to the right of `#??? = `
7. change the `en-us` to `es-es`
8. please include an attribution to you in the localization file, something like:
  * `// Translated by: [GitHubUserName](https://github.com/GitHubUserName)`
  * alternatively if you want another name from the KSP forums...
1. when done, PR it and you could reference this issue
2.  After it has been merged by me, you may delete your fork.

have fun and thank you! :octocat: 🎃

## GitHub

* Completed:
  * [x] assign
    * [x] zer0Kerbal
    * [x] Repo Localization Project
    * [x] Label: type: localization
    * [x] Label: help-wanted
    * [x] hacktoberfest
    * [x] good-first-issue
    * [x] contributions-welcome
    * [x] beginner-friendly
    * [x] Milestone: Localization - Master

### below done by @zer0Kerbal

* Update
  * Documentation
    * [x] [readme.md] 🔢
    * [x] [release.md] 🧾
  * docs/
    * [x] docs/[localization.md]
  * Update Social Media
  * [x] GitHub (automated) (zer0Kerbal/zer0Kerbal)
  * [x] CurseForge
  * [x] Reddit
  * [x] Twitter @zer0Kerbal
  * [x] Forum
  * [x] Patreon
  * [x] SpaceDock
  * [x] CKAN (automated)

[lclztn]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/readme.md  "Localization"
[qs]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/quickstart.md "Quick Start"

[ES]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/master/img/ES.png "Español"

this file: © All Rights Reserved by zer0Kerbal

**Comment by alvarohghg** [comment]
Hi, could I get this assigned?

**Comment by alvarohghg** [comment]
is the string section called "Agencies" the only one needed to be translated?

**Comment by zer0Kerbal** [comment]
both sections please
tags are used to search in game (editor) for items in this pack 
since Monero is a proper name, should just need something like _'Banderas Monero'_ 

again, thank you.

```
		#QBMF-name = Monero Flags
		#QBMF-abbv = QBMF
		#QBMF-tags = monero flags qbmf

		// Agencies
		#QBMF-agency-name = Monero
		#QBMF-agency-desc = A growing IT startup providing anonymous kryptocurrency. Despite accusations of supporting illegal snacks trade, they mostly invest in high-risk industry such as aerospace. Agent: Duke Dr. General PH.D Economics and CFO: Hohmannson Kermin
		#QBMF-agency-descR
```
